#!/bin/bash

export PATH="$PATH:/PATH/TO/jr-config/build/bin:/PATH/TO/jr-config/bin"

git_subdir() {
    BASE=$(git rev-parse --show-toplevel 2>/dev/null)

    if [[ -n "$BASE" ]] ; then
        SUB="\[\e[38;5;38m\]$(rmpre "$PWD" "$BASE")"
    else
        BASE="$PWD"
    fi

    echo "\[\e[38;5;25m\]$(tildefy "$BASE")$SUB\[\e[0m\]"
}

tildefy() {
    if [[ "$1" =~ ^"$HOME"(/|$) ]] ; then
        echo "~$(rmpre "$1" "$HOME")"
    else
        echo "$1"
    fi
}

jobs_sum() {
    local stopped=$(jobs -sp | wc -l | sed -e 's/^ *//' -e 's/ *$//')
    local running=$(jobs -rp | wc -l | sed -e 's/^ *//' -e 's/ *$//')
    if ((running+stopped)) ; then
        local out=
        if ((running)) ; then
            out=$out$running
        fi
        if ((running)) && ((stopped)) ; then
            out=$out,
        fi
        if ((stopped)) ; then
            out=$out'\[\e[38;5;88m\]'$stopped'\[\e[38;5;242m\]'
        fi
        echo '\[\e[38;5;242m\]'[$out]'\[\e[0m\]'
    fi
}

alias j=jobs
alias dash="apid-cli -c dashboard-metadata"

. $(brew --prefix)/etc/bash_completion
. $(brew --prefix)/etc/bash_completion.d/git-prompt.sh

stty -ixon

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM=1
GIT_PS1_SHOWCOLORHINTS=1
PROMPT_COMMAND='__git_ps1 "$(jobs_sum)\[\e[1;38;5;22m\]\u\[\e[0m\] $(git_subdir)" "\\\$ " " %s"'

complete -o default -W "logs.janrain.com logs-eu.janrain.com 3.dev-app.janraincapture.com 1.app.janraincapture.com pse.janrain.com 2.test-app.janraincapture.com 1.eu-app.janraincapture.com 1.au-app.janraincapture.com customer-dev.janrain.com capture-data-migration.janrain.com capture-data-migration-eu.janrain.com build.janraincapture.com capture-data-migration-au.janrain.com ubu1.local waldo.janrain.com jump-cn.janrain.com 1-app-prod.cn.janrain.com logs-prod.cn.janrain.com" ssh sftp
complete -o default -W "right bottom left" mvdock
complete -o default -W "YES NO" showhidden
